// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfetezkxmoqzxzzixnoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmZXRlemt4bW9xenh6eml4bm9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDQyNzQsImV4cCI6MjA1ODk4MDI3NH0.XfS6YNEPWns9054nZoq1NV9pD6nezMkgeOrTPn00Xjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);